name: BaseCoords
version: 1.0
main: fr.ikalaga.basecoords.Main
api-version: 1.21
commands:
  setbase:
    description: Enregistrer une base
  base:
    description: Voir les coordonnées d'une base
  deletebase:
    description: Supprime une base